### ISSUE TITLE
iOS native target support

### ISSUE THREAD

**Issue by maicol07** [DatL4g/Sekret#2]
Hi,
is it possible to generate iOS native files? I've added 
```kotlin
kotlin {
  // ....
  iosArm64 {
    binaries {
      sharedLib()
    }
  }
  iosSimulatorArm64 {
    binaries {
      sharedLib()
    }
  }
  iosX64 {
    binaries {
      sharedLib()
    }
  }
// ....
}
val jniNativeMain by creating {
		// ....
      iosMain.orNull?.dependsOn(this)
    }

    val jniMain by creating {
	// ....
      iosMain.orNull?.dependsOn(this)
    }
```

However, this gives me a lot of undefined references errors.
Can you help me?
Thanks

**Comment by DatL4g** [comment]
Yes it's possible, just edit the `build.gradle.kts` to your needs.

I'm not a iOS developer myself, however I think you have to configure it like this:

```kotlin
iosX64{
	binaries { 
		sharedLib() // choose one
		staticLib() // choose one
		framework { 
			baseName = "sekret"
			isStatic = // depends on the chosen at top
		}
	}
}
```

As I said I'm not a iOS developer so I can't test or make sure all references are resolved, but the library is fully native compatible.

**Comment by maicol07** [comment]
🤔 I don't think it works... I get the same errors on two machines (Windows and MacOS) when generating native libraries...
These are all the not-found references:
![image](https://github.com/DatL4g/Sekret/assets/9463142/f2ac7daa-6f36-4084-bf1c-2c3de5edc5bf)

**Comment by DatL4g** [comment]
Which version do you use?

**Comment by DatL4g** [comment]
Please update to version `2.0.0-alpha-01`. It's safe to use for your purpose.
It's important to bump the version in `sekret/build.gradle.kts` (the file we discussed before) as well.

Make sure to follow the "upgrade guide": https://github.com/DatL4g/Sekret/releases

**Comment by DatL4g** [comment]
After updating the gradle plugin you could also use the new `generateSekretBuildScript` gradle task, to make sure everything is setup correctly.

**Comment by maicol07** [comment]
Same issue even after upgrading to 2.0a1. The build script command actually removes iosMain from the jni blocks

**Comment by DatL4g** [comment]
Can you please post the build script

**Comment by DatL4g** [comment]
iOS doesn't work in the jni build, since iOS doesn't run on the JVM.
Only `android`, `linux`, `macos` and `windows` is supported there.

Removing `iosMain` from `jniNativeMain` and `jniMain` will resolve all issues.
iOS runs completely native so all you need are the ios targets, native bindings are generated accordingly.

**Comment by maicol07** [comment]
Ok, thank you. However, doing this I can't find the Sekret and NativeLoader classes. How can I access my secrets?

**Comment by DatL4g** [comment]
The NativeLoader is needed on android and jvm only.

iOS (and other native targets) have direct bindings.
Please take a look here: https://kotlinlang.org/docs/native-objc-interop.html#top-level-functions-and-properties

**Comment by maicol07** [comment]
Works! Thank you!
For future readers, if you have a secret like this:
```ini
MY_SECRET="123"
```

Just use it as a function in your iosMain code:
```kotlin
mySecret()
```

**Comment by DatL4g** [comment]
This may change in the next version to `Sekret.mySecret()`

**Comment by maicol07** [comment]
Yeah, that may be better, so it can be used without extra code in the common module

**Comment by DatL4g** [comment]
New release has a common `Sekret` class now

https://github.com/DatL4g/Sekret/releases/tag/v2.0.0-alpha-02
