### ISSUE TITLE
Sekret is not working with the new compose resources library

### ISSUE THREAD

**Issue by maicol07** [DatL4g/Sekret#3]
Sekret is not copying native libs to androidMain when using Compose 1.6 or 1.5.11 + experimental resources library.
https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-images-resources.html

**Comment by DatL4g** [comment]
Native libraries should not be placed under resources and may not even work if so.

There is a `androidJNIFolder` property:

```gradle
/**
	the directory for android should point to `../src/(android)Main/jniLibs` 
	use main or androidMain depending on your setup
	the jniLibs folder needs to be next to the AndroidManifest.xml
*/
sekret {
	properties {
		androidJNIFolder.set(directory)
	}
}
```

Same for desktop `desktopComposeResourcesFolder`:  
Take a look at the sample directory for a desktop example.

```gradle
/**
	the directory for desktop should point to `../resources` 
	NOT src/main/resources
	https://github.com/JetBrains/compose-multiplatform/blob/master/tutorials/Native_distributions_and_local_execution/README.md#adding-files-to-packaged-application
*/
sekret {
	properties {
		desktopComposeResourcesFolder.set(directory)
	}
}
```

**Comment by DatL4g** [comment]
Then you can call the `createAndCopySekretNativeLibrary` gradle task and the binaries will be copied to the specified dirs and can be loaded.

- On Android `NativeLoader.loadLibrary("sekret")`
- On Desktop: as described in the README

**Comment by maicol07** [comment]
Thank you! Setting the JNI folder manually did the trick!
